### PR TITLE
Dev-3364 Crypto Miner > Add instruction for proper mining in AMD cards

### PR DESCRIPTION
**Pull request by jonelrempis**
## Ticket references
- [Dev-3364](https://freedom.myjetbrains.com/youtrack/issue/Dev-3364)

## Summary of changes
- Added amd card instructions

## Checklist
- [ ] bugfix
- [x] new feature
- [ ] breaking change
- [ ] added unit tests
- [ ] changes introduced has been discussed and approved
- [ ] requires manual testing
- [ ] documentation has been updated

## Testing
Test instructions are [here](https://gitlab.com/mcnfreedom/vn-team/crypto/crypto.miner.client/merge_requests/282#b9bc2a5050f17be648233a9957bf797f4aa17f31)

### CODE REVIEW

**Review by cedricabuso — APPROVED** [review]

**Review by wilbertverayin — APPROVED** [review]

**Review by wilbertverayin — APPROVED** [review]

**Review by ferdrian-melarpis — APPROVED** [review]

**Review by zsannenmariano — APPROVED** [review]

**Comment by cedricabuso** [comment]
image

**Comment by ferdrian-melarpis** [comment]
image

**Comment by pandafox** [comment]
Please also test to verify AMD tab doesn't show when there's no AMD hardware

**Comment by jonelrempis** [comment]
@pandafox 
-  Tested on `RIG02`  (With AMD Hardware)
image

- Tested on `CMR-01` (with Intel Hardware)
image

**Review by pandafox — APPROVED** [review]

**Pull request merged**
